#include "csv_reader.hpp"
#include <fstream>
#include <stdexcept>
#include <unordered_map>
namespace ppibench { namespace {
std::vector<std::string> parse(const std::string& line){std::vector<std::string> f;std::string x;bool q=false;for(size_t i=0;i<line.size();++i){char c=line[i];if(c=='\"'){if(q&&i+1<line.size()&&line[i+1]=='\"'){x+='\"';++i;}else q=!q;}else if(c==','&&!q){f.push_back(x);x.clear();}else x+=c;}f.push_back(x);return f;}
std::string esc(const std::string&s){if(s.find_first_of(",\"\n\r")==std::string::npos)return s;std::string o="\"";for(char c:s)o+=(c=='\"'?"\"\"":std::string(1,c));return o+'\"';}
int toi(const std::string&s){try{return s.empty()?0:std::stoi(s);}catch(...){return 0;}}
}
std::vector<CaseRecord> load_cases_csv(const std::string& path,const std::string& sf,size_t maxc){std::ifstream in(path);if(!in)throw std::runtime_error("Cannot open "+path);std::string l;if(!std::getline(in,l))throw std::runtime_error("Empty CSV");auto h=parse(l);std::unordered_map<std::string,size_t> idx;for(size_t i=0;i<h.size();++i)idx[h[i]]=i;for(auto n:{"case_id","wkt_p","wkt_q"})if(!idx.count(n))throw std::runtime_error(std::string("Missing column ")+n);auto get=[&](const auto&v,const std::string&n){auto it=idx.find(n);return it==idx.end()||it->second>=v.size()?std::string():v[it->second];};std::vector<CaseRecord> out;while(std::getline(in,l)){if(l.empty())continue;auto v=parse(l);CaseRecord r;r.case_id=get(v,"case_id");r.split=get(v,"split");r.case_class=get(v,"case_class");r.vertices_p=toi(get(v,"vertices_p"));r.vertices_q=toi(get(v,"vertices_q"));r.wkt_p=get(v,"wkt_p");r.wkt_q=get(v,"wkt_q");r.difficulty_level=get(v,"difficulty_level");if(sf!="all"&&!r.split.empty()&&r.split!=sf)continue;out.push_back(std::move(r));if(maxc&&out.size()>=maxc)break;}return out;}
void write_results_csv(const std::string& path,const std::vector<OperationResult>& rs){std::ofstream o(path);if(!o)throw std::runtime_error("Cannot write "+path);o<<"case_id,backend,intersection_ms,union_ms,difference_ms,symmetric_difference_ms,total_ms,intersection_area,union_area,difference_area,symmetric_difference_area,valid_intersection,valid_union,valid_difference,valid_symmetric_difference,status\n";o.setf(std::ios::fixed);o.precision(9);for(auto&r:rs)o<<esc(r.case_id)<<','<<esc(r.backend)<<','<<r.intersection_ms<<','<<r.union_ms<<','<<r.difference_ms<<','<<r.symmetric_difference_ms<<','<<r.total_ms<<','<<r.intersection_area<<','<<r.union_area<<','<<r.difference_area<<','<<r.symmetric_difference_area<<','<<r.valid_intersection<<','<<r.valid_union<<','<<r.valid_difference<<','<<r.valid_symmetric_difference<<','<<esc(r.status)<<'\n';}
}
